name: Release and Deploy to NPM

on:
  workflow_dispatch:

jobs:
  release:
    permissions:
      pull-requests: write
      contents: write
      id-token: write
      issues: write

    name: Release new version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: yarn

      - name: Install dependencies and build 🔧
        run: yarn && yarn build

      - name: Release new version and deploy 🚀
        run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
